<?php

return [
    // 日本车
    'レクサス' => 'lexus',
    'トヨタ' => 'toyota',
    '日産' => 'nissan',
    'ホンダ' => 'honda',
    'マツダ' => 'mazda',
    'スバル' => 'subaru',
    'スズキ' => 'suzuki',
    '三菱' => 'mitsubishi',
    'ダイハツ' => 'daihatsu',
    'いすゞ' => 'isuzu',
    '光岡自動車' => 'mitsuoka',
    'トミーカイラ' => 'tommykaira',
    '日野自動車' => 'hino',
    '三菱ふそう' => 'mitsubishi-fuso',

    // 德国车
    'メルセデス・ベンツ' => 'mercedes-benz',
    'AMG' => 'amg',
    'マイバッハ' => 'maybach',
    'スマート' => 'smart',
    'メルセデスAMG' => 'mercedes-amg',
    'BMW' => 'bmw',
    'BMWアルピナ' => 'bmw-alpina',
    'アウディ' => 'audi',
    'フォルクスワーゲン' => 'volkswagen',
    'オペル' => 'opel',
    'ポルシェ' => 'porsche',
    'ミニ' => 'mini',
    'メルセデス・マイバッハ' => 'mercedes-maybach',

    // 英国车
    'ロールスロイス' => 'rolls-royce',
    'ベントレー' => 'bentley',
    'ジャガー' => 'jaguar',
    'デイムラー' => 'daimler',
    'ランドローバー' => 'land-rover',
    'アストンマーチン' => 'aston-martin',
    'ロータス' => 'lotus',
    'マクラーレン' => 'mclaren',
    'TVR' => 'tvr',
    'MG' => 'mg',
    'ローバー' => 'rover',
    'ケータハム' => 'caterham',
    'モーガン' => 'morgan',

    // 美国车
    'キャデラック' => 'cadillac',
    'シボレー' => 'chevrolet',
    'ビュイック' => 'buick',
    'ポンティアック' => 'pontiac',
    'サターン' => 'saturn',
    'ハマー' => 'hummer',
    'GMC' => 'gmc',
    'リンカーン' => 'lincoln',
    'マーキュリー' => 'mercury',
    'クライスラー' => 'chrysler',
    'ダッジ' => 'dodge',
    'ジープ' => 'jeep',
    'テスラ' => 'tesla',
    '米国トヨタ' => 'toyota-usa',
    '米国日産' => 'nissan-usa',
    '米国ホンダ' => 'honda-usa',
    '米国スバル' => 'subaru-usa',
    '米国三菱' => 'mitsubishi-usa',
    '米国マツダ' => 'mazda-usa',
    '米国いすゞ' => 'isuzu-usa',

    // 意大利车
    'アルファロメオ' => 'alfa-romeo',
    'フェラーリ' => 'ferrari',
    'ランボルギーニ' => 'lamborghini',
    'マセラティ' => 'maserati',
    'アバルト' => 'abarth',

    // 法国车
    'プジョー' => 'peugeot',
    'ルノー' => 'renault',
    'シトロエン' => 'citroen',
    'DSオートモビル' => 'ds-automobiles',
    'アルピーヌ' => 'alpine',

    // 瑞典车
    'ボルボ' => 'volvo',
    'サーブ' => 'saab',

    // 其他国家
    'ドンカーブート' => 'donkervoort',
    'ヒョンデ' => 'hyundai',
    'KTM' => 'ktm',

    // 反向映射（英文到日文）
    'lexus' => 'レクサス',
    'toyota' => 'トヨタ',
    'nissan' => '日産',
    'honda' => 'ホンダ',
    'mazda' => 'マツダ',
    'subaru' => 'スバル',
    'suzuki' => 'スズキ',
    'mitsubishi' => '三菱',
    'daihatsu' => 'ダイハツ',
    'isuzu' => 'いすゞ',
    'mitsuoka' => '光岡自動車',
    'tommykaira' => 'トミーカイラ',
    'hino' => '日野自動車',
    'mitsubishi-fuso' => '三菱ふそう',
    'mercedes-benz' => 'メルセデス・ベンツ',
    'amg' => 'AMG',
    'maybach' => 'マイバッハ',
    'smart' => 'スマート',
    'mercedes-amg' => 'メルセデスAMG',
    'bmw' => 'BMW',
    'bmw-alpina' => 'BMWアルピナ',
    'audi' => 'アウディ',
    'volkswagen' => 'フォルクスワーゲン',
    'opel' => 'オペル',
    'porsche' => 'ポルシェ',
    'mini' => 'ミニ',
    'mercedes-maybach' => 'メルセデス・マイバッハ',
    'rolls-royce' => 'ロールスロイス',
    'bentley' => 'ベントレー',
    'jaguar' => 'ジャガー',
    'daimler' => 'デイムラー',
    'land-rover' => 'ランドローバー',
    'aston-martin' => 'アストンマーチン',
    'lotus' => 'ロータス',
    'mclaren' => 'マクラーレン',
    'tvr' => 'TVR',
    'mg' => 'MG',
    'rover' => 'ローバー',
    'caterham' => 'ケータハム',
    'morgan' => 'モーガン',
    'cadillac' => 'キャデラック',
    'chevrolet' => 'シボレー',
    'buick' => 'ビュイック',
    'pontiac' => 'ポンティアック',
    'saturn' => 'サターン',
    'hummer' => 'ハマー',
    'gmc' => 'GMC',
    'lincoln' => 'リンカーン',
    'mercury' => 'マーキュリー',
    'chrysler' => 'クライスラー',
    'dodge' => 'ダッジ',
    'jeep' => 'ジープ',
    'tesla' => 'テスラ',
    'toyota-usa' => '米国トヨタ',
    'nissan-usa' => '米国日産',
    'honda-usa' => '米国ホンダ',
    'subaru-usa' => '米国スバル',
    'mitsubishi-usa' => '米国三菱',
    'mazda-usa' => '米国マツダ',
    'isuzu-usa' => '米国いすゞ',
    'alfa-romeo' => 'アルファロメオ',
    'ferrari' => 'フェラーリ',
    'lamborghini' => 'ランボルギーニ',
    'maserati' => 'マセラティ',
    'abarth' => 'アバルト',
    'peugeot' => 'プジョー',
    'renault' => 'ルノー',
    'citroen' => 'シトロエン',
    'ds-automobiles' => 'DSオートモビル',
    'alpine' => 'アルピーヌ',
    'volvo' => 'ボルボ',
    'saab' => 'サーブ',
    'donkervoort' => 'ドンカーブート',
    'hyundai' => 'ヒョンデ',
    'ktm' => 'KTM',
];
